create database eventticketingsystem
    with owner postgres;

create table public.tbl_businessemail
(
    businessemailid   varchar   not null
        constraint tbl_businessemail_pk
            primary key,
    businessemailcode varchar   not null,
    fullname          varchar   not null,
    phone             varchar   not null,
    email             varchar   not null,
    createdby         varchar   not null,
    createdat         timestamp not null,
    modifiedby        varchar,
    modifiedat        timestamp,
    deleteflag        boolean   not null
);

alter table public.tbl_businessemail
    owner to postgres;

create table public.tbl_ticketprice
(
    ticketpriceid   varchar        not null
        constraint tbl_ticketprice_pk
            primary key,
    ticketpricecode varchar        not null,
    tickettypecode  varchar        not null,
    ticketprice     numeric(20, 2) not null,
    ticketquantity  integer        not null,
    createdby       varchar        not null,
    createdat       timestamp      not null,
    modifiedby      varchar,
    modifiedat      timestamp,
    deleteflag      boolean        not null
);

alter table public.tbl_ticketprice
    owner to postgres;

create table public.tbl_tickettype
(
    tickettypeid   varchar   not null
        constraint tbl_tickettype_pk
            primary key,
    tickettypecode varchar   not null,
    eventcode      varchar   not null,
    tickettypename varchar   not null,
    createdby      varchar   not null,
    createdat      timestamp not null,
    modifiedby     varchar,
    modifiedat     timestamp,
    deleteflag     boolean   not null
);

alter table public.tbl_tickettype
    owner to postgres;

create table public.tbl_venuetype
(
    venuetypeid   varchar   not null
        constraint tbl_venuetype_pk
            primary key,
    venuetypecode varchar   not null,
    venuetypename varchar   not null,
    createdby     varchar   not null,
    createdat     timestamp not null,
    modifiedby    varchar,
    modifiedat    timestamp,
    deleteflag    boolean   not null
);

alter table public.tbl_venuetype
    owner to postgres;

create table public.tbl_transactionticket
(
    transactionticketid   varchar        not null
        constraint tbl_transactionticket_pk
            primary key,
    transactionticketcode varchar        not null,
    transactioncode       varchar        not null,
    ticketcode            varchar        not null,
    qrimage               varchar        not null,
    price                 numeric(20, 2) not null,
    createdby             varchar        not null,
    createdat             timestamp      not null,
    modifiedby            varchar,
    modifiedat            timestamp,
    deleteflag            boolean        not null
);

alter table public.tbl_transactionticket
    owner to postgres;

create table public.tbl_verification
(
    verificationid   varchar   not null
        constraint tbl_verification_pk
            primary key,
    verificationcode varchar   not null,
    email            varchar   not null,
    expiredtime      timestamp not null,
    isused           boolean   not null,
    createdby        varchar   not null,
    createdat        timestamp not null,
    modifiedby       varchar,
    modifiedat       timestamp,
    deleteflag       boolean   not null
);

alter table public.tbl_verification
    owner to postgres;

create table public.tbl_sequence
(
    sequenceid   integer generated by default as identity
        constraint tbl_sequence_pk
            primary key,
    uniquename   varchar   not null,
    sequenceno   varchar   not null,
    sequencedate timestamp not null,
    sequencetype varchar   not null,
    eventcode    varchar,
    deleteflag   boolean   not null
);

alter table public.tbl_sequence
    owner to postgres;

create table public.tbl_venue
(
    venueid       varchar   not null
        constraint tbl_venue_pk
            primary key,
    venuecode     varchar   not null,
    venuetypecode varchar   not null,
    venuename     varchar   not null,
    description   text,
    address       varchar   not null,
    capacity      integer   not null,
    facilities    text,
    addons        text,
    venueimage    varchar   not null,
    createdby     varchar   not null,
    createdat     timestamp not null,
    modifiedby    varchar,
    modifiedat    timestamp,
    deleteflag    boolean   not null
);

alter table public.tbl_venue
    owner to postgres;

create table public.tbl_admin
(
    adminid      varchar   not null
        constraint tbl_admin_pk
            primary key,
    admincode    varchar   not null,
    fullname     varchar   not null,
    username     varchar   not null,
    email        varchar   not null,
    phone        varchar   not null,
    password     varchar   not null,
    profileimage varchar,
    isfirsttime  boolean   not null,
    createdby    varchar   not null,
    createdat    timestamp not null,
    modifiedby   varchar,
    modifiedat   timestamp,
    deleteflag   boolean   not null
);

alter table public.tbl_admin
    owner to postgres;

create table public.tbl_login
(
    loginid               varchar   not null
        constraint tbl_login_pk
            primary key,
    admincode             varchar   not null,
    username              varchar   not null,
    sessionid             varchar   not null,
    refreshtoken          varchar   not null,
    refreshtokenexpiresat timestamp not null,
    loginstatus           varchar   not null,
    createdby             varchar   not null,
    createdat             timestamp not null,
    modifiedby            varchar,
    modifiedat            timestamp,
    deleteflag            boolean   not null
);

alter table public.tbl_login
    owner to postgres;

create table public.tbl_businessowner
(
    businessownerid   varchar   not null
        constraint tbl_businessowner_pk
            primary key,
    businessownercode varchar   not null,
    fullname          varchar   not null,
    email             varchar   not null,
    phone             varchar   not null,
    createdby         varchar   not null,
    createdat         timestamp not null,
    modifiedby        varchar,
    modifiedat        timestamp,
    deleteflag        boolean   not null
);

alter table public.tbl_businessowner
    owner to postgres;

create table public.tbl_event
(
    eventid             varchar                  not null
        constraint tbl_event_pk
            primary key,
    eventcode           varchar                  not null,
    venuecode           varchar                  not null,
    eventname           varchar                  not null,
    eventcategorycode   varchar                  not null,
    startdate           timestamp with time zone not null,
    enddate             timestamp with time zone not null,
    isactive            boolean                  not null,
    eventstatus         varchar                  not null,
    businessownercode   varchar                  not null,
    totalticketquantity integer                  not null,
    soldoutcount        integer                  not null,
    uniquename          varchar                  not null,
    createdby           varchar                  not null,
    createdat           timestamp                not null,
    modifiedby          varchar,
    modifiedat          timestamp,
    deleteflag          boolean                  not null
);

alter table public.tbl_event
    owner to postgres;

create table public.tbl_eventcategory
(
    eventcategoryid   varchar   not null
        constraint tbl_eventcategory_pk
            primary key,
    eventcategorycode varchar   not null,
    categoryname      varchar   not null,
    createdby         varchar   not null,
    createdat         timestamp not null,
    modifiedby        varchar,
    modifiedat        timestamp,
    deleteflag        boolean   not null
);

alter table public.tbl_eventcategory
    owner to postgres;

create table public.tbl_transaction
(
    transactionid   varchar        not null
        constraint tbl_transaction_pk
            primary key,
    transactioncode varchar        not null,
    fullname        varchar        not null,
    gender          varchar        not null,
    phone           varchar        not null,
    email           varchar        not null,
    eventcode       varchar        not null,
    status          varchar        not null,
    paymenttype     varchar        not null,
    transactiondate timestamp      not null,
    totalamount     numeric(20, 2) not null,
    createdby       varchar        not null,
    createdat       timestamp      not null,
    modifiedby      varchar,
    modifiedat      timestamp,
    deleteflag      boolean        not null
);

alter table public.tbl_transaction
    owner to postgres;

create table public.tbl_ticket
(
    ticketid        varchar   not null
        constraint tbl_ticket_pk
            primary key,
    ticketcode      varchar   not null,
    ticketpricecode varchar   not null,
    isused          boolean   not null,
    soldout         boolean   not null,
    createdby       varchar   not null,
    createdat       timestamp not null,
    modifiedby      varchar,
    modifiedat      timestamp,
    deleteflag      boolean   not null
);

alter table public.tbl_ticket
    owner to postgres;

create function public.sp_sequencecode(id integer) returns character varying
    language plpgsql
as
$$
DECLARE
    value int;
    incremented_value varchar(6);
BEGIN
    SELECT sequenceno::int + 1 INTO value
    FROM tbl_sequence
    WHERE sequenceid = id
    AND deleteflag = false;

    incremented_value := LPAD(value::text, 6, '0');

    UPDATE tbl_sequence
    SET sequenceno = incremented_value,
        sequencedate = now()
    WHERE sequenceid = id
    AND deleteflag = false;

    RETURN incremented_value;
END;
$$;

alter function public.sp_sequencecode(integer) owner to postgres;

create function public.sp_sequencecode_bulk(id integer, quantity integer)
    returns TABLE(sequence_number character varying)
    language plpgsql
as
$$
DECLARE
    current_val int;
    new_val int;
    i int := 1;
BEGIN
    SELECT sequenceno::int INTO current_val
    FROM tbl_sequence
    WHERE sequenceid = id
      AND deleteflag = false
    FOR UPDATE;

    IF current_val IS NULL THEN
        RAISE EXCEPTION 'Sequence not found or deleted';
    END IF;

    new_val := current_val + quantity;

    UPDATE tbl_sequence
    SET sequenceno = LPAD(new_val::text, 6, '0'),
        sequencedate = now()
    WHERE sequenceid = id
      AND deleteflag = false;

    WHILE i <= quantity LOOP
        sequence_number := LPAD((current_val + i)::text, 6, '0');
        RETURN NEXT;
        i := i + 1;
    END LOOP;

END;
$$;

alter function public.sp_sequencecode_bulk(integer, integer) owner to postgres;

create function public.sp_ticket_info(p_ticketcode character varying)
    returns TABLE(ticketpricecode character varying, ticketprice numeric, tickettypecode character varying, eventcode character varying, startdate timestamp with time zone, enddate timestamp with time zone, eventname character varying, tickettypename character varying, venuename character varying)
    language plpgsql
as
$$
BEGIN
    RETURN QUERY
        SELECT tp.ticketpricecode,
               tp.ticketprice,
               tp.tickettypecode,
               tt.eventcode,
               e.startdate,
               e.enddate,
               e.eventname,
               tt.tickettypename,
               v.venuename
        FROM tbl_ticket t
                 INNER JOIN tbl_ticketprice tp ON t.ticketpricecode = tp.ticketpricecode
                 INNER JOIN tbl_tickettype tt ON tp.tickettypecode = tt.tickettypecode
                 INNER JOIN tbl_event e ON tt.eventcode = e.eventcode
                 INNER JOIN tbl_venue v ON e.venuecode = v.venuecode
        WHERE t.ticketcode = p_ticketcode
          AND t.deleteflag = false
          AND tp.deleteflag = false
          AND e.deleteflag = false
          AND tt.deleteflag = false
          AND v.deleteflag = false;
END;
$$;

alter function public.sp_ticket_info(varchar) owner to postgres;
